# Generated by Django 2.0.2 on 2018-03-26 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainFunc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='userAvatar'),
        ),
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(default='Hello there I am using ImageX!'),
        ),
        migrations.AddField(
            model_name='member',
            name='usr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='userImg'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainFunc.Category'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default='Add photo description here.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
