# Generated by Django 2.0.2 on 2018-03-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0002_auto_20180326_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='static/userImg'),
        ),
    ]
