# Generated by Django 2.0.2 on 2018-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0003_auto_20180326_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='mainFunc/static/userImg'),
        ),
    ]
