# Generated by Django 2.0.2 on 2018-03-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainFunc', '0006_auto_20180327_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uploadBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainFunc.Member'),
        ),
    ]
